# Generated by Django 3.1.3 on 2020-11-29 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CardApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='txt',
            new_name='edit_text',
        ),
    ]
