# Generated by Django 3.1.3 on 2020-11-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardApp', '0002_auto_20201129_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='edit_text',
            name='TopLiNav1',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст пункта меню 1'),
        ),
        migrations.AddField(
            model_name='edit_text',
            name='TopLiNav2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст пункта меню 2'),
        ),
        migrations.AddField(
            model_name='edit_text',
            name='TopLiNav3',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст пункта меню 3'),
        ),
        migrations.AddField(
            model_name='edit_text',
            name='TopLiNav4',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст пункта меню 4'),
        ),
        migrations.AddField(
            model_name='edit_text',
            name='TopLiNav5',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст пункта меню 5'),
        ),
        migrations.AddField(
            model_name='edit_text',
            name='TopLiNav6',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст пункта меню 6'),
        ),
        migrations.AddField(
            model_name='edit_text',
            name='TopLiNav7',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст пункта меню 7'),
        ),
    ]
