# Generated by Django 3.1.3 on 2020-11-30 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardApp', '0003_auto_20201130_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='edit_text',
            name='AboutButton',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст кнопки второго сектора'),
        ),
        migrations.AddField(
            model_name='edit_text',
            name='AboutCounterNumber1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Изменить цифры счетчика второго сектора 1'),
        ),
        migrations.AddField(
            model_name='edit_text',
            name='AboutCounterNumber2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Изменить цифры счетчика второго сектора 2'),
        ),
        migrations.AddField(
            model_name='edit_text',
            name='AboutCounterNumber3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Изменить цифры счетчика второго сектора 3'),
        ),
        migrations.AddField(
            model_name='edit_text',
            name='AboutCounterNumber4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Изменить цифры счетчика второго сектора 4'),
        ),
        migrations.AddField(
            model_name='edit_text',
            name='AboutCounterTitle2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст под счетчиком второго сектора 2'),
        ),
        migrations.AddField(
            model_name='edit_text',
            name='AboutCounterTitle3',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст под счетчиком второго сектора 3'),
        ),
        migrations.AddField(
            model_name='edit_text',
            name='AboutCounterTitle4',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст под счетчиком второго сектора 4'),
        ),
        migrations.AddField(
            model_name='edit_text',
            name='AboutLi1',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст пункта второго сектора 1'),
        ),
        migrations.AddField(
            model_name='edit_text',
            name='AboutLi2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст пункта второго сектора 2'),
        ),
        migrations.AddField(
            model_name='edit_text',
            name='AboutLi3',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст пункта второго сектора 3'),
        ),
        migrations.AddField(
            model_name='edit_text',
            name='AboutSectionH2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить название тега h2 во второй секции'),
        ),
        migrations.AddField(
            model_name='edit_text',
            name='AboutSectionP',
            field=models.TextField(blank=True, null=True, verbose_name='Изменить текст под тегом h2 во второй секции'),
        ),
        migrations.AddField(
            model_name='edit_text',
            name='AboutSectionTextArea1',
            field=models.TextField(blank=True, null=True, verbose_name='Изменить текст первой колонки во второй секции'),
        ),
        migrations.AddField(
            model_name='edit_text',
            name='AboutSectionTextArea2',
            field=models.TextField(blank=True, null=True, verbose_name='Изменить текст второй колонки во второй секции'),
        ),
    ]
