# Generated by Django 3.1.3 on 2020-12-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardApp', '0003_auto_20201211_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myjob',
            name='MyJobClient',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя или названия клиента'),
        ),
        migrations.AlterField(
            model_name='myjob',
            name='MyJobClientTitle',
            field=models.CharField(blank=True, default=' клиент', max_length=200, null=True, verbose_name='Названия пункта клиент'),
        ),
    ]
