# Generated by Django 3.1.3 on 2020-11-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardApp', '0004_auto_20201130_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='edit_text',
            name='AboutCounterTitle1',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст под счетчиком второго сектора 1'),
        ),
    ]
