# Generated by Django 3.1.3 on 2020-12-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardApp', '0004_auto_20201211_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myjob',
            name='slug',
            field=models.SlugField(default='TextTitle', help_text='Ссылка создается автоматически из названия продукта', max_length=200, unique=True, verbose_name='Ссылка на работу'),
        ),
    ]
