# Generated by Django 3.1.3 on 2020-12-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardApp', '0005_auto_20201211_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TopFirstH1', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст первого H1')),
                ('TopFirstH2', models.CharField(blank=True, default='Ваш текст', max_length=150, null=True, verbose_name='Изменить текст первого H2')),
                ('GetStartedBtn', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст первой кнопки')),
                ('TopCardBlockTitle1', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить название первого карт блока')),
                ('TopCardBlockText1', models.TextField(blank=True, null=True, verbose_name='Изменить текст первого карт блока')),
                ('TopCardBlockTitle2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить название второго карт блока')),
                ('TopCardBlockText2', models.TextField(blank=True, null=True, verbose_name='Изменить текст второго карт блока')),
                ('TopCardBlockTitle3', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить название третьего карт блока')),
                ('TopCardBlockText3', models.TextField(blank=True, null=True, verbose_name='Изменить текст третьего карт блока')),
                ('TopCardBlockTitle4', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить название четвертого карт блока')),
                ('TopCardBlockText4', models.TextField(blank=True, null=True, verbose_name='Изменить текст четвертого карт блока')),
            ],
        ),
        migrations.CreateModel(
            name='nav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст пункта меню 1')),
            ],
        ),
        migrations.DeleteModel(
            name='TopNavAndHero',
        ),
    ]
