# Generated by Django 3.1.3 on 2020-12-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardApp', '0005_edit_text_aboutcountertitle1'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TextReviews', models.TextField(blank=True, null=True, verbose_name='Текст отзыва')),
                ('PhotoReviews', models.ImageField(upload_to='', verbose_name='Фото клиента')),
                ('FioReviews', models.CharField(blank=True, max_length=250, null=True, verbose_name='Имя фамилия клиента')),
                ('RoleReviews', models.CharField(blank=True, max_length=250, null=True, verbose_name='роль клиента')),
            ],
        ),
        migrations.RenameModel(
            old_name='edit_text',
            new_name='EditTtext',
        ),
    ]
