# Generated by Django 3.1.3 on 2020-12-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardApp', '0006_auto_20201212_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav',
            name='SlugNav',
            field=models.SlugField(default='some', unique=True, verbose_name='пункт меню'),
            preserve_default=False,
        ),
    ]
