# Generated by Django 3.1.3 on 2020-12-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardApp', '0006_auto_20201202_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhotoTeam', models.ImageField(upload_to='', verbose_name='Фото сотрудника')),
                ('FioTeam', models.CharField(blank=True, max_length=250, null=True, verbose_name='Имя фамилия сотрудника')),
                ('RoleTeam', models.CharField(blank=True, max_length=250, null=True, verbose_name='роль сотрудника')),
            ],
        ),
    ]
