# Generated by Django 3.1.3 on 2020-12-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardApp', '0007_nav_slugnav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nav',
            name='SlugNav',
            field=models.CharField(max_length=400, unique=True, verbose_name='Ссылка или якорь пункта меню'),
        ),
    ]
