# Generated by Django 3.1.3 on 2020-12-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardApp', '0007_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='PhotoReviews',
            field=models.ImageField(upload_to='reviews', verbose_name='Фото клиента'),
        ),
        migrations.AlterField(
            model_name='team',
            name='PhotoTeam',
            field=models.ImageField(upload_to='team', verbose_name='Фото сотрудника'),
        ),
    ]
