# Generated by Django 3.1.3 on 2020-12-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardApp', '0008_auto_20201203_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AboutSectionH2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить название тега h2 во второй секции')),
                ('AboutSectionP', models.TextField(blank=True, null=True, verbose_name='Изменить текст под тегом h2 во второй секции')),
                ('AboutSectionTextArea1', models.TextField(blank=True, null=True, verbose_name='Изменить текст первой колонки во второй секции')),
                ('AboutSectionTextArea2', models.TextField(blank=True, null=True, verbose_name='Изменить текст второй колонки во второй секции')),
                ('AboutLi1', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст пункта второго сектора 1')),
                ('AboutLi2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст пункта второго сектора 2')),
                ('AboutLi3', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст пункта второго сектора 3')),
                ('AboutButton', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст кнопки второго сектора')),
            ],
        ),
        migrations.CreateModel(
            name='CountsSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CounterNumber1', models.IntegerField(blank=True, null=True, verbose_name='Изменить цифры счетчика второго сектора 1')),
                ('CounterTitle1', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст под счетчиком второго сектора 1')),
                ('CounterNumber2', models.IntegerField(blank=True, null=True, verbose_name='Изменить цифры счетчика второго сектора 2')),
                ('CounterTitle2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст под счетчиком второго сектора 2')),
                ('CounterNumber3', models.IntegerField(blank=True, null=True, verbose_name='Изменить цифры счетчика второго сектора 3')),
                ('CounterTitle3', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст под счетчиком второго сектора 3')),
                ('CounterNumber4', models.IntegerField(blank=True, null=True, verbose_name='Изменить цифры счетчика второго сектора 4')),
                ('CounterTitle4', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст под счетчиком второго сектора 4')),
            ],
        ),
        migrations.CreateModel(
            name='TopNavAndHero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TopLiNav1', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст пункта меню 1')),
                ('TopLiNav2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст пункта меню 2')),
                ('TopLiNav3', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст пункта меню 3')),
                ('TopLiNav4', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст пункта меню 4')),
                ('TopLiNav5', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст пункта меню 5')),
                ('TopLiNav6', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст пункта меню 6')),
                ('TopLiNav7', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст пункта меню 7')),
                ('TopFirstH1', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст первого H1')),
                ('TopFirstH2', models.CharField(blank=True, default='Ваш текст', max_length=150, null=True, verbose_name='Изменить текст первого H2')),
                ('GetStartedBtn', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст первой кнопки')),
                ('TopCardBlockTitle1', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить название первого карт блока')),
                ('TopCardBlockText1', models.TextField(blank=True, null=True, verbose_name='Изменить текст первого карт блока')),
                ('TopCardBlockTitle2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить название второго карт блока')),
                ('TopCardBlockText2', models.TextField(blank=True, null=True, verbose_name='Изменить текст второго карт блока')),
                ('TopCardBlockTitle3', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить название третьего карт блока')),
                ('TopCardBlockText3', models.TextField(blank=True, null=True, verbose_name='Изменить текст третьего карт блока')),
                ('TopCardBlockTitle4', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить название четвертого карт блока')),
                ('TopCardBlockText4', models.TextField(blank=True, null=True, verbose_name='Изменить текст четвертого карт блока')),
            ],
        ),
        migrations.DeleteModel(
            name='EditTtext',
        ),
    ]
