# Generated by Django 3.1.3 on 2020-12-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardApp', '0008_auto_20201212_0556'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContactH3', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить заговолок')),
                ('ContactP', models.TextField(blank=True, null=True, verbose_name='Текст под заговолком')),
                ('LocationTitle', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить название пункта локакция')),
                ('location', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить локакцию')),
                ('EmailTitle', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить название пункта почта')),
                ('Email', models.EmailField(max_length=254, verbose_name='Ваша почта')),
                ('CallTitle', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ваш телефон')),
            ],
        ),
        migrations.CreateModel(
            name='JobText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobTextH3', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить заговолок')),
                ('JobTextP', models.TextField(blank=True, null=True, verbose_name='Текст под заговолком')),
            ],
        ),
        migrations.CreateModel(
            name='TeamText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeamTextH3', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить заговолок')),
                ('TeamTextP', models.TextField(blank=True, null=True, verbose_name='Текст под заговолком')),
            ],
        ),
    ]
