# Generated by Django 3.1.3 on 2020-12-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardApp', '0009_auto_20201203_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutVideoSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Some', models.URLField(verbose_name='Ссылка на изображение или видео')),
                ('AboutVideoSectionH3', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить заговолок')),
                ('AboutVideoSectionP', models.TextField(blank=True, null=True, verbose_name='Текст под заговолком')),
                ('AboutVideoSectionLi1', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст пункта 1')),
                ('AboutVideoSectionLi2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст пункта 2')),
                ('AboutVideoSectionLi3', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст пункта 3')),
                ('AboutVideoSectionLi4', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст пункта 4')),
                ('AboutVideoSectionEndP', models.TextField(blank=True, null=True, verbose_name='Изменить текст в конце секции')),
            ],
        ),
    ]
