# Generated by Django 3.1.3 on 2020-12-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardApp', '0009_contact_jobtext_teamtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Call',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ваш телефон'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='CallTitle',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить название пункта телефон'),
        ),
    ]
