# Generated by Django 3.1.3 on 2020-12-12 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CardApp', '0010_auto_20201212_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Call',
            new_name='call',
        ),
    ]
