# Generated by Django 3.1.3 on 2020-12-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardApp', '0010_aboutvideosection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutvideosection',
            name='Some',
        ),
        migrations.AddField(
            model_name='aboutvideosection',
            name='AboutVideoSectionUrl',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ссылка на изображение или видео'),
        ),
    ]
