# Generated by Django 3.1.3 on 2020-12-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardApp', '0011_auto_20201204_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutvideosection',
            name='AboutVideoSectionPlug',
            field=models.ImageField(default='', upload_to='AboutVideoSection', verbose_name='Картинка для заглушки видео'),
            preserve_default=False,
        ),
    ]
