# Generated by Django 3.1.3 on 2020-12-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardApp', '0011_auto_20201212_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='myjob',
            name='CheckLink',
            field=models.BooleanField(default=False, verbose_name='Поставьте эту галочку, если хотите добавить ссыльку на работу на внешнем сайте'),
        ),
        migrations.AddField(
            model_name='myjob',
            name='ExternalLink',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Внешная ссылька на работу'),
        ),
    ]
