# Generated by Django 3.1.3 on 2020-12-16 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CardApp', '0012_auto_20201215_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsection',
            name='AboutLi1',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='AboutLi2',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='AboutLi3',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='AboutSectionH2',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='AboutSectionTextArea1',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='AboutSectionTextArea2',
        ),
    ]
