# Generated by Django 3.1.3 on 2020-12-04 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardApp', '0012_aboutvideosection_aboutvideosectionplug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutvideosection',
            name='AboutVideoSectionPlug',
            field=models.ImageField(help_text='Рекомендованное разрешение для заглушки: 1024 х 760', upload_to='AboutVideoSection', verbose_name='Картинка для заглушки видео'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='PhotoReviews',
            field=models.ImageField(help_text='Рекомендованное разрешение для фото: 400 х 400', upload_to='reviews', verbose_name='Фото клиента'),
        ),
        migrations.AlterField(
            model_name='team',
            name='PhotoTeam',
            field=models.ImageField(help_text='Рекомендованное разрешение для фото: 400 х 400', upload_to='team', verbose_name='Фото сотрудника'),
        ),
    ]
