# Generated by Django 3.1.3 on 2020-12-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardApp', '0013_auto_20201204_0427'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialsAndSevicesText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TestimonialsH3', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить заговолок секции Testimonials')),
                ('TestimonialsP', models.TextField(blank=True, null=True, verbose_name='Изменить текст под заговолком Testimonials')),
                ('SevicesH3', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить заговолок секции Sevices')),
                ('SevicesP', models.TextField(blank=True, null=True, verbose_name='Изменить текст под заговолком Sevices')),
                ('SevicesCardBlockTitle1', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить название первого карт блока')),
                ('SevicesCardBlockText1', models.TextField(blank=True, null=True, verbose_name='Изменить текст первого карт блока')),
                ('SevicesCardBlockTitle2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить название второго карт блока')),
                ('SevicesCardBlockText2', models.TextField(blank=True, null=True, verbose_name='Изменить текст второго карт блока')),
                ('SevicesCardBlockTitle3', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить название третьего карт блока')),
                ('SevicesCardBlockText3', models.TextField(blank=True, null=True, verbose_name='Изменить текст третьего карт блока')),
                ('SevicesCardBlockTitle4', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить название четвертого карт блока')),
                ('SevicesCardBlockText4', models.TextField(blank=True, null=True, verbose_name='Изменить текст четвертого карт блока')),
                ('SevicesCardBlockTitle5', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить название пятого карт блока')),
                ('SevicesCardBlockText5', models.TextField(blank=True, null=True, verbose_name='Изменить текст пятого карт блока')),
                ('SevicesCardBlockTitle6', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить название шестого карт блока')),
                ('SevicesCardBlockText6', models.TextField(blank=True, null=True, verbose_name='Изменить текст шестого карт блока')),
            ],
        ),
        migrations.AlterField(
            model_name='aboutvideosection',
            name='AboutVideoSectionUrl',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
