# Generated by Django 3.1.3 on 2020-12-16 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CardApp', '0013_auto_20201216_0418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutvideosection',
            name='AboutVideoSectionEndP',
        ),
        migrations.RemoveField(
            model_name='aboutvideosection',
            name='AboutVideoSectionH3',
        ),
        migrations.RemoveField(
            model_name='aboutvideosection',
            name='AboutVideoSectionLi1',
        ),
        migrations.RemoveField(
            model_name='aboutvideosection',
            name='AboutVideoSectionLi2',
        ),
        migrations.RemoveField(
            model_name='aboutvideosection',
            name='AboutVideoSectionLi3',
        ),
        migrations.RemoveField(
            model_name='aboutvideosection',
            name='AboutVideoSectionLi4',
        ),
    ]
