# Generated by Django 3.1.3 on 2020-12-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardApp', '0014_auto_20201204_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='CtaSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CtaH3', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст заголовка')),
                ('CtaP', models.TextField(blank=True, null=True, verbose_name='Изменить текст блока')),
                ('CtaBtn', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст кнопки')),
            ],
        ),
        migrations.CreateModel(
            name='GenericAsk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GenericAskLi', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст вопроса')),
                ('GenericAskP', models.TextField(blank=True, null=True, verbose_name='Изменить текст ответа')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsSectionText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuestionsSectionTextH3', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст заголовка')),
                ('QuestionsSectionTextP', models.TextField(blank=True, null=True, verbose_name='Изменить текст блока')),
            ],
        ),
    ]
