# Generated by Django 3.1.3 on 2020-12-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardApp', '0014_auto_20201217_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logotype', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
