# Generated by Django 3.1.3 on 2020-12-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardApp', '0015_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocNet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SocIcon', models.CharField(choices=[('adobe', 'adobe'), ('airbnb', 'airbnb'), ('algolia', 'algolia'), ('amazon', 'amazon'), ('android', 'android'), ('angular', 'angular'), ('apple', 'apple'), ('audible', 'audible'), ('baidu', 'baidu'), ('behance', 'behance'), ('bing', 'bing'), ('bitcoin', 'bitcoin'), ('blogger', 'blogger'), ('bootstrap', 'bootstrap'), ('chrome', 'chrome'), ('codepen', 'codepen'), ('creative-commons', 'creative-commons'), ('css3', 'css3'), ('dailymotion', 'dailymotion'), ('deviantart', 'deviantart'), ('dev-to', 'dev-to'), ('digg', 'digg'), ('digitalocean', 'digitalocean'), ('discord', 'discord'), ('discourse', 'discourse'), ('dribbble', 'dribbble'), ('dropbox', 'dropbox'), ('drupal', 'drupal'), ('ebay', 'ebay'), ('edge', 'edge'), ('etsy', 'etsy'), ('facebook', 'facebook'), ('figma', 'figma'), ('firefox', 'firefox'), ('flickr', 'flickr'), ('foursquare', 'foursquare'), ('git', 'git'), ('github', 'github'), ('gitlab', 'gitlab'), ('google', 'google'), ('imdb', 'imdb'), ('instagram', 'instagram'), ('internet-explorer', 'internet-explorer'), ('invision', 'invision'), ('javascript', 'javascript'), ('joomla', 'joomla'), ('jquery', 'jquery'), ('jsfiddle', 'jsfiddle'), ('kickstarter', 'kickstarter'), ('less', 'less'), ('linkedin', 'linkedin'), ('magento', 'magento'), ('mailchimp', 'mailchimp'), ('mastercard', 'mastercard'), ('medium', 'medium'), ('medium-old', 'medium-old'), ('messenger', 'messenger'), ('microsoft', 'microsoft'), ('nodejs', 'nodejs'), ('opera', 'opera'), ('patreon', 'patreon'), ('paypal', 'paypal'), ('periscope', 'periscope'), ('pinterest', 'pinterest'), ('play-play', 'play-play'), ('pocket', 'pocket'), ('product-hunt', 'product-hunt'), ('quora', 'quora'), ('react', 'react'), ('redbubble', 'redbubble'), ('reddit', 'reddit'), ('redux', 'redux'), ('sass', 'sass'), ('shopify', 'shopify'), ('skype', 'skype'), ('slack', 'slack'), ('snapchat', 'snapchat'), ('soundcloud', 'soundcloud'), ('spotify', 'spotify'), ('squarespace', 'squarespace'), ('stack', 'stack'), ('stripe', 'stripe'), ('telegram', 'telegram'), ('trello', 'trello'), ('tumblr', 'tumblr'), ('twitch', 'twitch'), ('twitter', 'twitter'), ('unsplash', 'unsplash'), ('vimeo', 'vimeo'), ('visa', 'visa'), ('vk', 'vk'), ('vuejs', 'vuejs'), ('whatsapp', 'whatsapp'), ('wikipedia', 'wikipedia'), ('windows', 'windows'), ('wix', 'wix'), ('wordpress', 'wordpress'), ('yahoo', 'yahoo'), ('yelp', 'yelp'), ('youtube', 'youtube')], max_length=250, verbose_name='выберите соц.сеть либо иконку из списка')),
                ('SocUrl', models.URLField(verbose_name='Введите ссылку')),
            ],
        ),
    ]
