# Generated by Django 3.1.3 on 2020-12-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardApp', '0015_ctasection_genericask_questionssectiontext'),
    ]

    operations = [
        migrations.CreateModel(
            name='pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PricingH3', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст заголовка')),
                ('PricingP', models.TextField(blank=True, null=True, verbose_name='Изменить текст блока')),
                ('PricingTittleColumn1', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить название первой колонки')),
                ('PricingCurrencyColumn1', models.CharField(blank=True, choices=[('1', 'USD'), ('2', 'EUR'), ('3', 'RUB')], max_length=150, null=True, verbose_name='Изменить валюту первой колонки')),
                ('PricingPriceColumn1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Изменить цену первой колонки')),
                ('PricingMonthColumn1', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст после цены первой колонки')),
                ('PricingUl1Li1', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст первого пункта первой колонки')),
                ('PricingCheckUl1Li1', models.BooleanField(default=True, verbose_name='Включить или выключить пункт')),
                ('PricingUl1Li2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст второго пункта первой колонки')),
                ('PricingCheckUl1Li2', models.BooleanField(default=True, verbose_name='Включить или выключить пункт')),
                ('PricingUl1Li3', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст третьего пункта первой колонки')),
                ('PricingCheckUl1Li3', models.BooleanField(default=True, verbose_name='Включить или выключить пункт')),
                ('PricingUl1Li4', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст четвертого пункта первой колонки')),
                ('PricingCheckUl1Li4', models.BooleanField(default=True, verbose_name='Включить или выключить пункт')),
                ('PricingUl1Li5', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст второго пункта первой колонки')),
                ('PricingUl1bBtn', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст кнопки первой колонки')),
                ('PricingTittleColumn2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить название второй колонки')),
                ('PricingCurrencyColumn2', models.CharField(blank=True, choices=[('1', 'USD'), ('2', 'EUR'), ('3', 'RUB')], max_length=150, null=True, verbose_name='Изменить валюту второй колонки')),
                ('PricingPriceColumn2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Изменить цену второй колонки')),
                ('PricingMonthColumn2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст после цены второй колонки')),
                ('PricingCheckUl2Li1', models.BooleanField(default=True, verbose_name='Включить или выключить пункт')),
                ('PricingUl2Li2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст второго пункта второй колонки')),
                ('PricingCheckUl2Li2', models.BooleanField(default=True, verbose_name='Включить или выключить пункт')),
                ('PricingUl2Li3', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст третьего пункта второй колонки')),
                ('PricingCheckUl2Li3', models.BooleanField(default=True, verbose_name='Включить или выключить пункт')),
                ('PricingUl2Li4', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст четвертого пункта второй колонки')),
                ('PricingCheckUl2Li4', models.BooleanField(default=True, verbose_name='Включить или выключить пункт')),
                ('PricingUl2Li5', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст второго пункта второй колонки')),
                ('PricingUl1bBtn2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст кнопки второй колонки')),
                ('PricingTittleColumn3', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить название третий колонки')),
                ('PricingCurrencyColumn3', models.CharField(blank=True, choices=[('1', 'USD'), ('2', 'EUR'), ('3', 'RUB')], max_length=150, null=True, verbose_name='Изменить валюту третий колонки')),
                ('PricingPriceColumn3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Изменить цену третий колонки')),
                ('PricingMonthColumn32', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст после цены третий колонки')),
                ('PricingUl3Li1', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст первого пункта третий колонки')),
                ('PricingCheckUl3Li1', models.BooleanField(default=True, verbose_name='Включить или выключить пункт')),
                ('PricingUl3Li2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст второго пункта третий колонки')),
                ('PricingCheckUl3Li2', models.BooleanField(default=True, verbose_name='Включить или выключить пункт')),
                ('PricingUl3Li3', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст третьего пункта третий колонки')),
                ('PricingCheckUl3Li3', models.BooleanField(default=True, verbose_name='Включить или выключить пункт')),
                ('PricingUl3Li4', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст четвертого пункта третий колонки')),
                ('PricingCheckUl3Li4', models.BooleanField(default=True, verbose_name='Включить или выключить пункт')),
                ('PricingUl3Li5', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст второго пункта третий колонки')),
                ('PricingCheckUl1Li5', models.BooleanField(default=True, verbose_name='Включить или выключить пункт')),
                ('PricingUl1bBtn3', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст кнопки третий колонки')),
            ],
        ),
    ]
