# Generated by Django 3.1.3 on 2020-12-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardApp', '0016_pricing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricing',
            old_name='PricingMonthColumn32',
            new_name='PricingMonthColumn3',
        ),
        migrations.AddField(
            model_name='pricing',
            name='PricingUl2Li1',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст первого пункта второй колонки'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='PricingUl1Li5',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст пятого пункта первой колонки'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='PricingUl3Li5',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст пятого пункта третий колонки'),
        ),
    ]
