# Generated by Django 3.1.3 on 2020-12-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardApp', '0016_socnet'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLinksTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FooterLink', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст пункта меню')),
                ('SlugFooter', models.CharField(max_length=400, unique=True, verbose_name='Ссылка или якорь пункта меню')),
            ],
        ),
        migrations.CreateModel(
            name='FooterListHeaders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FooterRtitle1', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить первый заголовок перед первым списком')),
                ('FooterRtitle2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить второй заголовок перед вторым списком')),
            ],
        ),
        migrations.CreateModel(
            name='FooterSubscribeF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FooterSubh4', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить заголовок формы подписки')),
                ('FooterSubP', models.TextField(blank=True, null=True, verbose_name='Изменить текст формы подписки')),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='ContactH3',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить заголовок'),
        ),
        migrations.AlterField(
            model_name='jobtext',
            name='JobTextH3',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить заголовок'),
        ),
        migrations.AlterField(
            model_name='nav',
            name='nav',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст пункта меню'),
        ),
        migrations.AlterField(
            model_name='teamtext',
            name='TeamTextH3',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить заголовок'),
        ),
        migrations.AlterField(
            model_name='testimonialsandsevicestext',
            name='SevicesH3',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить заголовок секции Sevices'),
        ),
        migrations.AlterField(
            model_name='testimonialsandsevicestext',
            name='TestimonialsH3',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить заголовок секции Testimonials'),
        ),
    ]
