# Generated by Django 3.1.3 on 2020-12-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardApp', '0017_auto_20201205_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='PricingCheckUl2Li5',
            field=models.BooleanField(default=True, verbose_name='Включить или выключить пункт'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='PricingCheckUl3Li5',
            field=models.BooleanField(default=True, verbose_name='Включить или выключить пункт'),
        ),
    ]
