# Generated by Django 3.1.3 on 2020-12-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardApp', '0018_auto_20201205_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='PricingUl2Li5',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Изменить текст пятого пункта второй колонки'),
        ),
    ]
