# Generated by Django 3.1.3 on 2020-12-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardApp', '0019_auto_20201205_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='PricingCheckUl1Li1',
            field=models.BooleanField(default=True, verbose_name='Включить пункт'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='PricingCheckUl1Li2',
            field=models.BooleanField(default=True, verbose_name='Включить пункт'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='PricingCheckUl1Li3',
            field=models.BooleanField(default=True, verbose_name='Включить пункт'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='PricingCheckUl1Li4',
            field=models.BooleanField(default=True, verbose_name='Включить пункт'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='PricingCheckUl1Li5',
            field=models.BooleanField(default=True, verbose_name='Включить пункт'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='PricingCheckUl2Li1',
            field=models.BooleanField(default=True, verbose_name='Включить пункт'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='PricingCheckUl2Li2',
            field=models.BooleanField(default=True, verbose_name='Включить пункт'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='PricingCheckUl2Li3',
            field=models.BooleanField(default=True, verbose_name='Включить пункт'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='PricingCheckUl2Li4',
            field=models.BooleanField(default=True, verbose_name='Включить пункт'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='PricingCheckUl2Li5',
            field=models.BooleanField(default=True, verbose_name='Включить пункт'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='PricingCheckUl3Li1',
            field=models.BooleanField(default=True, verbose_name='Включить пункт'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='PricingCheckUl3Li2',
            field=models.BooleanField(default=True, verbose_name='Включить пункт'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='PricingCheckUl3Li3',
            field=models.BooleanField(default=True, verbose_name='Включить пункт'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='PricingCheckUl3Li4',
            field=models.BooleanField(default=True, verbose_name='Включить пункт'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='PricingCheckUl3Li5',
            field=models.BooleanField(default=True, verbose_name='Включить пункт'),
        ),
    ]
