from django.contrib import admin
from .models import *
# Register your models here.
admin.site.register(nav)
admin.site.register(hero)
admin.site.register(AboutSection)
admin.site.register(CountsSection)
admin.site.register(AboutVideoSection)
admin.site.register(reviews)
admin.site.register(TestimonialsAndSevicesText)
admin.site.register(CtaSection)
admin.site.register(pricing)
admin.site.register(TeamText)
admin.site.register(team)
admin.site.register(QuestionsSectionText)
admin.site.register(GenericAsk)
admin.site.register(JobText)
admin.site.register(Jobcategory)
admin.site.register(MyJob)
admin.site.register(contact)
